// Parameter values come from environment variables so secrets never appear on the command line.
// deploy.ps1 and deploy.sh export them from infra/deploy.env before running the deployment.
using './main.bicep'

param baseName = readEnvironmentVariable('BASE_NAME', 'secureshare')
param appServiceSku = readEnvironmentVariable('APP_SERVICE_SKU', 'B1')
param planName = readEnvironmentVariable('APP_SERVICE_PLAN', '')
param nodeVersion = readEnvironmentVariable('NODE_VERSION', '24-lts')
param storageLocation = readEnvironmentVariable('STORAGE_LOCATION', '')
param appLocation = readEnvironmentVariable('APP_LOCATION', '')
param authorityHost = readEnvironmentVariable('AUTHORITY_HOST', 'https://login.microsoftonline.com')
param tenantId = readEnvironmentVariable('TENANT_ID')
param allowedTenantIds = readEnvironmentVariable('ALLOWED_TENANT_IDS', '')
param clientId = readEnvironmentVariable('CLIENT_ID')
param clientSecret = readEnvironmentVariable('CLIENT_SECRET')
param sessionSecret = readEnvironmentVariable('SESSION_SECRET')
param baseUrl = readEnvironmentVariable('BASE_URL', '')
param linkTtlDays = int(readEnvironmentVariable('LINK_TTL_DAYS', '7'))
param maxUploadMb = int(readEnvironmentVariable('MAX_UPLOAD_MB', '100'))
param maxConcurrentUploads = int(readEnvironmentVariable('MAX_CONCURRENT_UPLOADS', '4'))
param scanPolicy = readEnvironmentVariable('SCAN_POLICY', 'required')
param scanGraceMinutes = int(readEnvironmentVariable('SCAN_GRACE_MINUTES', '2'))
param scanCapGbPerMonth = int(readEnvironmentVariable('SCAN_CAP_GB', '500'))
param containerName = readEnvironmentVariable('STORAGE_CONTAINER', 'uploads')
param storageAccountName = readEnvironmentVariable('STORAGE_ACCOUNT', '')
param webAppName = readEnvironmentVariable('WEB_APP_NAME', '')
param allowSharedKeyAccess = bool(readEnvironmentVariable('ALLOW_SHARED_KEY_ACCESS', 'false'))
param createRoleAssignment = bool(readEnvironmentVariable('CREATE_ROLE_ASSIGNMENT', 'true'))
param createTableRoleAssignment = bool(readEnvironmentVariable('CREATE_TABLE_ROLE_ASSIGNMENT', 'true'))
param auditRetentionDays = int(readEnvironmentVariable('AUDIT_RETENTION_DAYS', '730'))
param auditRole = readEnvironmentVariable('AUDIT_ROLE', 'Audit.Read')
